# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-04 16:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0004_addteam'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddPlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('contact_no', models.IntegerField()),
                ('address', models.TextField()),
                ('jersy_no', models.IntegerField()),
                ('position', models.CharField(choices=[('Striker', 'Striker'), ('MidFielder', 'MidFielder'), ('Defender', 'Defender'), ('GoalKeeper', 'GoalKeeper')], max_length=25)),
                ('upload_photo', models.ImageField(upload_to='players/')),
            ],
        ),
        migrations.AlterField(
            model_name='addteam',
            name='team_logo',
            field=models.ImageField(upload_to='teams_logo/'),
        ),
        migrations.AddField(
            model_name='addplayer',
            name='team_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Manager.AddTeam'),
        ),
    ]
