# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-18 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0008_auto_20190417_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='addtournments',
            name='is_registred',
            field=models.BooleanField(default=True),
        ),
    ]
