# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-18 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0009_addtournments_is_registred'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addtournments',
            name='is_registred',
            field=models.BooleanField(default=False),
        ),
    ]
