# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-27 05:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0010_auto_20190418_1017'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AddTournments',
        ),
    ]
