# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-27 05:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0011_delete_addtournments'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddTournments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_name', models.CharField(max_length=30)),
                ('t_venue', models.CharField(max_length=30)),
                ('s_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('e_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('r_fee', models.IntegerField()),
            ],
        ),
    ]
