# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-30 22:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0013_tournmentregistration'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddFixture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name_one', models.IntegerField()),
                ('team_name_two', models.IntegerField()),
                ('match_date', models.DateField()),
                ('match_time', models.TimeField()),
                ('venue', models.CharField(max_length=30)),
            ],
        ),
    ]
