# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-30 22:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0014_addfixture'),
    ]

    operations = [
        migrations.AddField(
            model_name='addfixture',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
