# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-06 21:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0015_addfixture_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='addfixture',
            name='tournment_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Manager.AddTournments'),
            preserve_default=False,
        ),
    ]
