# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-07 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0016_addfixture_tournment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='addfixture',
            name='match_name',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
