# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-09 06:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0016_addfixture_tournment_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddFixture_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_one', models.CharField(max_length=30)),
                ('team_two', models.CharField(max_length=30)),
                ('match_name', models.CharField(max_length=50)),
                ('match_date', models.DateField()),
                ('match_time', models.TimeField()),
                ('venue', models.CharField(max_length=30)),
                ('status', models.BooleanField(default=False)),
                ('tr_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Manager.AddTournments')),
            ],
        ),
        migrations.RemoveField(
            model_name='addfixture',
            name='tournment_id',
        ),
        migrations.DeleteModel(
            name='AddFixture',
        ),
    ]
