# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-07 19:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0017_addfixture_match_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_one', models.IntegerField()),
                ('score_two', models.IntegerField()),
                ('fixture_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Manager.AddFixture')),
                ('team_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Manager.AddTeam')),
                ('tournment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Manager.AddTournments')),
            ],
        ),
    ]
