# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-10 05:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0018_addpoints'),
    ]

    operations = [
        migrations.AddField(
            model_name='addpoints',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='addpoints',
            name='team_2_point',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
