# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-07 19:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0018_addresults'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addresults',
            name='team_id',
        ),
    ]
