# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-07 19:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0019_remove_addresults_team_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addresults',
            name='fixture_id',
        ),
    ]
