# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-12 03:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0021_auto_20190509_2220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addpoints',
            name='team_1_point',
        ),
        migrations.RemoveField(
            model_name='addpoints',
            name='team_2_point',
        ),
        migrations.AddField(
            model_name='addpoints',
            name='looser',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addpoints',
            name='winner',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
    ]
