# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-17 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0024_addgoalkeepersaves'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addgoalsandassist',
            name='assist_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
