# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-20 19:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0026_newkeeper'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('f_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Manager.AddFixture_table')),
                ('team_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Manager.AddTeam')),
            ],
        ),
    ]
